insert into team (Name, size) values ('Bartoletti-Hermiston', 1);
insert into team (Name, size) values ('Lowe and Sons', 7);
insert into team (Name, size) values ('Lowe-Gleichner', 9);
insert into team (Name, size) values ('Dibbert LLC', 6);
insert into team (Name, size) values ('VonRueden-Schulist', 9);
insert into team (Name, size) values ('Hand, Kulas and Langworth', 8);
insert into team (Name, size) values ('Champlin, Cole and Koelpin', 1);
insert into team (Name, size) values ('Douglas, Mosciski and Berge', 10);
insert into team (Name, size) values ('Hayes and Sons', 5);
insert into team (Name, size) values ('Nader Group', 5);
insert into team (Name, size) values ('Harber-Labadie', 10);
insert into team (Name, size) values ('Bayer, Waelchi and Kozey', 6);
insert into team (Name, size) values ('Dickinson Group', 8);
insert into team (Name, size) values ('Runte, Moen and Lakin', 1);
insert into team (Name, size) values ('Becker Inc', 9);
insert into team (Name, size) values ('Grimes-Oberbrunner', 7);
insert into team (Name, size) values ('Schultz Group', 7);
insert into team (Name, size) values ('Zemlak-Klein', 3);
insert into team (Name, size) values ('Bogan-Lynch', 2);
insert into team (Name, size) values ('Ward, Walsh and Herman', 8);
insert into team (Name, size) values ('White-Lesch', 3);
insert into team (Name, size) values ('Upton Inc', 9);
insert into team (Name, size) values ('Pollich-Jaskolski', 1);
insert into team (Name, size) values ('O''Reilly-Walsh', 8);
insert into team (Name, size) values ('Gleason, O''Conner and Hammes', 3);
insert into team (Name, size) values ('Hegmann, Okuneva and Schmidt', 8);
insert into team (Name, size) values ('Nikolaus-Sauer', 9);
insert into team (Name, size) values ('Gleichner LLC', 6);
insert into team (Name, size) values ('Russel LLC', 2);
insert into team (Name, size) values ('Gibson-Stanton', 8);
insert into team (Name, size) values ('Bergstrom, Harvey and Cartwright', 8);
insert into team (Name, size) values ('Monahan Group', 5);
insert into team (Name, size) values ('Donnelly Group', 10);
insert into team (Name, size) values ('Strosin LLC', 1);
insert into team (Name, size) values ('Weissnat Inc', 7);
insert into team (Name, size) values ('King-Hilpert', 5);
insert into team (Name, size) values ('Oberbrunner, Pagac and Torp', 1);
insert into team (Name, size) values ('O''Connell-Runolfsdottir', 5);
insert into team (Name, size) values ('Jacobs-Hane', 9);
insert into team (Name, size) values ('Stamm-Prosacco', 7);
insert into team (Name, size) values ('Pfeffer, Hegmann and Turcotte', 7);
insert into team (Name, size) values ('Flatley Inc', 3);
insert into team (Name, size) values ('Walker Group', 10);
insert into team (Name, size) values ('Zemlak LLC', 10);
insert into team (Name, size) values ('Veum-Strosin', 3);
insert into team (Name, size) values ('Batz Group', 1);
insert into team (Name, size) values ('Flatley, O''Kon and Stokes', 2);
insert into team (Name, size) values ('Goldner and Sons', 1);
insert into team (Name, size) values ('Walter-Kunde', 3);
insert into team (Name, size) values ('Jacobson, Schulist and Mraz', 6);
insert into team (Name, size) values ('Bosco-Schmidt', 3);
insert into team (Name, size) values ('Kertzmann Inc', 3);
insert into team (Name, size) values ('Hodkiewicz, Cronin and Bins', 4);
insert into team (Name, size) values ('Welch-Bauch', 1);
insert into team (Name, size) values ('Watsica, Pacocha and Green', 4);
insert into team (Name, size) values ('Rempel-Parisian', 7);
insert into team (Name, size) values ('Haag Inc', 1);
insert into team (Name, size) values ('Deckow-Kertzmann', 5);
insert into team (Name, size) values ('Roberts-Murphy', 8);
insert into team (Name, size) values ('Little and Sons', 8);
insert into team (Name, size) values ('Corwin-Satterfield', 7);
insert into team (Name, size) values ('MacGyver-Jacobson', 1);
insert into team (Name, size) values ('Wilderman-Bergnaum', 3);
insert into team (Name, size) values ('Turcotte-Baumbach', 8);
insert into team (Name, size) values ('Lynch LLC', 6);
insert into team (Name, size) values ('Flatley, Conn and Powlowski', 9);
insert into team (Name, size) values ('Jast, Barrows and Cole', 5);
insert into team (Name, size) values ('Prohaska-Nicolas', 4);
insert into team (Name, size) values ('Schaefer-Kunze', 10);
insert into team (Name, size) values ('Daniel Inc', 3);
insert into team (Name, size) values ('Lueilwitz, Erdman and Metz', 9);
insert into team (Name, size) values ('Batz, McDermott and Weissnat', 8);
insert into team (Name, size) values ('Hackett LLC', 7);
insert into team (Name, size) values ('Ebert-Rice', 8);
insert into team (Name, size) values ('Borer LLC', 3);
insert into team (Name, size) values ('Powlowski, Russel and Gutkowski', 8);
insert into team (Name, size) values ('Keebler-Mills', 1);
insert into team (Name, size) values ('Tromp-Prohaska', 8);
insert into team (Name, size) values ('Bernier-Klocko', 6);
insert into team (Name, size) values ('Purdy, Hettinger and Feest', 7);
insert into team (Name, size) values ('Keebler-Wilderman', 2);
insert into team (Name, size) values ('Koss-Dare', 1);
insert into team (Name, size) values ('Donnelly Inc', 4);
insert into team (Name, size) values ('Schuppe, Predovic and Jerde', 10);
insert into team (Name, size) values ('Bednar-Blanda', 6);
insert into team (Name, size) values ('Paucek and Sons', 2);
insert into team (Name, size) values ('Nolan and Sons', 9);
insert into team (Name, size) values ('Ruecker, Stokes and Konopelski', 10);
insert into team (Name, size) values ('Sporer Group', 10);
insert into team (Name, size) values ('Jerde LLC', 7);
insert into team (Name, size) values ('Vandervort-Skiles', 1);
insert into team (Name, size) values ('Muller, Heller and Luettgen', 6);
insert into team (Name, size) values ('Bashirian-Bartoletti', 1);
insert into team (Name, size) values ('Hyatt, Conroy and Monahan', 5);
insert into team (Name, size) values ('Ward, Paucek and Bogisich', 8);
insert into team (Name, size) values ('Harris, Wolff and Howell', 6);
insert into team (Name, size) values ('Douglas-Casper', 6);
insert into team (Name, size) values ('Sipes-Bergstrom', 9);
insert into team (Name, size) values ('Lang and Sons', 9);
insert into team (Name, size) values ('Franecki-Schuppe', 1);
insert into team (Name, size) values ('Becker LLC', 4);
insert into team (Name, size) values ('Hessel Inc', 5);
insert into team (Name, size) values ('Dibbert, Bahringer and Lowe', 7);
insert into team (Name, size) values ('Kautzer Inc', 6);
insert into team (Name, size) values ('Wintheiser, McLaughlin and Jacobi', 1);
insert into team (Name, size) values ('Leannon-Bergstrom', 9);
insert into team (Name, size) values ('Beier, Mueller and Weissnat', 5);
insert into team (Name, size) values ('Bogan Inc', 8);
insert into team (Name, size) values ('Corwin Group', 7);
insert into team (Name, size) values ('Zemlak Inc', 6);
insert into team (Name, size) values ('Deckow-Carter', 3);
insert into team (Name, size) values ('Graham LLC', 4);
insert into team (Name, size) values ('Swaniawski, Rice and Schimmel', 5);
insert into team (Name, size) values ('Walker, Gerhold and Hills', 4);
insert into team (Name, size) values ('Haley and Sons', 9);
insert into team (Name, size) values ('Lindgren Group', 1);
insert into team (Name, size) values ('Fritsch Group', 9);
insert into team (Name, size) values ('Schamberger-Beahan', 8);
insert into team (Name, size) values ('Wuckert-Johns', 2);
insert into team (Name, size) values ('Parisian, McDermott and Ruecker', 4);
insert into team (Name, size) values ('Kunze-Mann', 2);
insert into team (Name, size) values ('Hyatt, Mayer and Hagenes', 8);
insert into team (Name, size) values ('Quitzon-Legros', 2);
insert into team (Name, size) values ('Kuphal Group', 2);
insert into team (Name, size) values ('Weimann-Lebsack', 4);
insert into team (Name, size) values ('Bogisich Inc', 2);
insert into team (Name, size) values ('Russel, Mante and Morar', 4);
insert into team (Name, size) values ('Kreiger, Franecki and Hickle', 3);
insert into team (Name, size) values ('Runolfsdottir, Littel and Jerde', 2);
insert into team (Name, size) values ('Stoltenberg and Sons', 8);
insert into team (Name, size) values ('Torp, Treutel and Bradtke', 6);
insert into team (Name, size) values ('Sipes and Sons', 9);
insert into team (Name, size) values ('Stracke, Schulist and Yundt', 9);
insert into team (Name, size) values ('Parisian, Abernathy and Hauck', 5);
insert into team (Name, size) values ('Spencer, Von and Cole', 5);
insert into team (Name, size) values ('Bartell LLC', 9);
insert into team (Name, size) values ('Ullrich, Doyle and Wisozk', 6);
insert into team (Name, size) values ('Bergstrom, Kub and Schaefer', 1);
insert into team (Name, size) values ('Beer, VonRueden and O''Connell', 5);
insert into team (Name, size) values ('Treutel and Sons', 2);
insert into team (Name, size) values ('Sanford and Sons', 6);
insert into team (Name, size) values ('Mante-Gerhold', 4);
insert into team (Name, size) values ('Zemlak and Sons', 2);
insert into team (Name, size) values ('Heathcote-Feeney', 6);
insert into team (Name, size) values ('O''Hara-Rohan', 4);
insert into team (Name, size) values ('Franecki, Beahan and Corwin', 6);
insert into team (Name, size) values ('Schmidt-Kub', 1);
insert into team (Name, size) values ('Grant, Gusikowski and McClure', 5);
insert into team (Name, size) values ('Larkin, Mueller and Brekke', 6);
insert into team (Name, size) values ('Block Group', 10);